### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by innocuoussoul** [mthyden/PhillipsHueSIMPLSharp#1]
Are you still maintaining this? I'm very interested in it :)

**Comment by mthyden** [comment]
I am, just moved states, and transitioned to a new role at Crestron so my development has slowed a bit however, the module as it stands is already in production at a few locations including my house. My house only has 3 rooms/groups and 8 bulbs however the largest deployment I have done with them was 6 rooms/groups with upwards of 30-40 bulbs.

Future updates I will be tackling will be adding some threading and queuing support for under the hood performance improvements and changing the IDing schema I currently use which currently relies on a room ID numerical value rather then the room name which would be easier for a programmer to work with.

I ran into a bug in the field where the Scenes and Groups bulb lists were not in the same order which I used to reconcile which scenes are tied to which room, so given that unusual issue I added manual scene IDs as a parameter field.

**Comment by innocuoussoul** [comment]
Thats awesome, congrats on the new role! :) 

I've been trying to get this up and running as a test with a CP3 and a tsw-1052 and can't seem to get anything to move... I'm still poking at it though :) 
Looking forward to the optimization!

**Comment by mthyden** [comment]
Is your bridge discovered by the prof module? Make sure that's discovered and is pulling an API key otherwise nothing will work. Then make sure with one of the room modules you do an initial poll
