### ISSUE TITLE
Exception after connect - most function not working

### ISSUE THREAD

**Issue by ir0n87** [mthyden/PhillipsHueSIMPLSharp#12]
Morning! Thanks a lot for sharing your job! I'm a Crestron programmer from Italy and i know it's a lot of hard work!

My home system is composed with:
- old round hub with latest fw
- 4 colur bulb
- rmc3 with latest fw

Hub is correctly registered. After that i can power on and power off my room good and i can change colurs with graph.
Scene selection is not working (no names at all), increase/decrease button keep only decrease to minimum light output and after stay at the intensity.

Here the output of text console:

Get IP of Bridge complete...
4 Bulbs discovered
1 Rooms discovered
11 Scenes discovered
Error getting Room data: System.ArgumentOutOfRangeException: 
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at HueLights.HueRoom.GetRoom()
   at UserModule_HUELIGHTSROOM_R1_5.UserModuleClass_HUELIGHTSROOM_R1_5.GETINFO_OnPush_0(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.p()

Same exception each button i press related to that push event.
Any help?

Thanks!

**Comment by mthyden** [comment]
Bombing out on the rooms/groups for some reason, do you have just 1 room assigned with all four bulbs in it or multiple rooms?

 

If you can send me the json output of your bridge for the groups, instructions on how to do this are on the Philips Hue API website.

 

When you say increase/decrease races to the minimum, is that under the room module or individual light module?

**Comment by ir0n87** [comment]
Just factory resetted my hub to be sure to start with clean config...
Now my key changed... how delete key in crestron data store?

I've found this command in crestron console:

DATASTOREDEL

but ask for global or local... Can't get the correct syntax.

Thanks!

**Comment by mthyden** [comment]
I added a signal on the processor module Hue API Reset.

On Jul 2, 2018, at 5:51 AM, ir0n87 <notifications@github.com> wrote:

Just factory resetted my hub to be sure to start with clean config...
Now my key changed... how delete key in crestron data store?

I've found this command in crestron console:

DATASTOREDEL

but ask for global or local... Can't get the correct syntax.

Thanks!

**Comment by mthyden** [comment]
if your still having trouble it is a local entry not global and you may need the descriptor field for the entry in the datastore to delete it, the name of the entry is “apikey”, if that still doesn’t work a initialize or betacleanup will wipe it as well.

On Jul 2, 2018, at 5:51 AM, ir0n87 <notifications@github.com> wrote:

Just factory resetted my hub to be sure to start with clean config...
Now my key changed... how delete key in crestron data store?

I've found this command in crestron console:

DATASTOREDEL

but ask for global or local... Can't get the correct syntax.

Thanks!

**Comment by ir0n87** [comment]
Ok fixed! Factory reset of my HUB solved the problem... Maybe some ghost scene... Don't know!
Many thanks for your help!
