### ISSUE TITLE
Simpl Windows file is corrupted.

### ISSUE THREAD

**Issue by arikadiusz** [mthyden/PhillipsHueSIMPLSharp#18]
If you download the archive as zip from git hub all line endings are replaced. This should be marked as binary in .gitignore maybe ?

**Comment by mthyden** [comment]
Huh. Yeah possibly will need to look, this is the first someone has brought this up, not sure how others are dealing with it then.

**Comment by arikadiusz** [comment]
I had this problem with our repos on bitbucket ages ago. I belive it's a win10 bug for git but never looked more in depth into this so may be wrong.

here is the post on crestron labs :
http://www.crestronlabs.com/showthread.php?11822-Win10-git-smw-git&highlight=line+endings

**Comment by mthyden** [comment]
Got it will take a look, shortly.

**Comment by mthyden** [comment]
read the post, have no idea where to set the binary encoding flag. I'm not fully familiar with the git command line I use GitHub Desktop app to manage my repos, if you want a dropbox link to the sample program I can send it to you. https://www.dropbox.com/s/o0yez5k0v1ory4f/PhillipsHue%20Demo%20v2.2_compiled.zip?dl=0

**Comment by mthyden** [comment]
I've added the appropriate lines to the gitattributes file
