### ISSUE TITLE
Bulb doesn't come Online

### ISSUE THREAD

**Issue by ErwinDukker** [mthyden/PhillipsHueSIMPLSharp#20]
In my system the Hue Bridge is online and working properly. It recongnise 3 bulbs in 2 rooms.
But the 3 bulb doesn't come online in Simpl Debugger.
They work properly with the Hue App.

Any idea?

**Comment by mthyden** [comment]
Not sure, I typically just control rooms not bulbs myself, I’ll test it this weekend and see what’s what.

**Comment by ErwinDukker** [comment]
Hi Monte,

 

It was my fault. I made a mistake with the bulbname. Now its working perfectly. Thanks for creating this module.

 

Best regards,

Erwin Dukker

 

Van: Monte Thyden <notifications@github.com> 
Verzonden: zaterdag 5 oktober 2019 02:55
Aan: mthyden/PhillipsHueSIMPLSharp <PhillipsHueSIMPLSharp@noreply.github.com>
CC: ErwinDukker <info@edukker.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mthyden/PhillipsHueSIMPLSharp] Bulb doesn't come Online (#20)

 

Not sure, I typically just control rooms not bulbs myself, I’ll test it this weekend and see what’s what.

**Comment by mthyden** [comment]
Awesome, glad its working for you. Apologies your issue completely fell off my radar.
