### ISSUE TITLE
Sensor ?

### ISSUE THREAD

**Issue by metronomeout** [mthyden/PhillipsHueSIMPLSharp#22]
Hello, 

Thanks for your work ! I would like to know if you planed to implement sensors in that driver ?

**Comment by mthyden** [comment]
I do and that work has already started however is of low priority. The challenge is the polling rate to get accurate sensor feedback like motion and such without sacrificing reliability of the lighting manipulation.

Selfishly I have a Crestron Home system with a bunch of sensors I use to manipulate my Hue system so I have no pressing need.

Is there a specific implementation / use case you are looking for?
