### ISSUE TITLE
Groups/bulbs with umlaut characters not working

### ISSUE THREAD

**Issue by leissnerj** [mthyden/PhillipsHueSIMPLSharp#24]
For example, one of my groups is named "Köket", but in toolbox it's reported as "K??ket"

I found a fix myself for it, first time messing around in Simpl#, took me longer than I will admit.

in HttpConnect.cs at line 42

public string Request(string url, string cmd, Crestron.SimplSharp.Net.Http.RequestType reqtype)
		{
			_request.Url.Parse(url);
			_request.RequestType = reqtype;
			if (cmd == null)
			{
				_request.ContentString = "";
			}
			else
			{
				_request.ContentString = cmd;
			}            
			_response = _client.Dispatch(_request);
            **_response.Encoding = Encoding.UTF8; //JL addition**
			String jsontext = _response.ContentString;
			return jsontext;
		}

also add 
using System.Text;

**Comment by mthyden** [comment]
Thanks for tracking that down. I’ll update my project this weekend build/test/ and post hopefully baring any issues.

**Comment by mthyden** [comment]
my latest commit addresses this issue.
