### ISSUE TITLE
Multiple Ligth or Room changes at same time won't work

### ISSUE THREAD

**Issue by ErwinDukker** [mthyden/PhillipsHueSIMPLSharp#26]
Hi,

Im having issues, changing the level of multiple bulbs or rooms at the same time. From my crestron system I call a preset with multiple Hue lights in it. Randomly some of them are working fine, and some are ignored. If I do change the lights one by one, it works fine. 
Is this something you can solve or do we have to accept the way Hue works, and we have to find a work-around?

**Comment by mthyden** [comment]
you should stagger the functions if you're trying to affect multiple bulbs at the same time. It's certainly possible that multiple REST calls may be accepted by the bridge however my architecture isn't structured to work that way. The native hue app doesn't work that way as they push you to use groups/rooms to affect multiple bulbs in an area. If you desire that feature I would break up bulb groups and adjust those levels rather then a group of individual bulbs.
