### ISSUE TITLE
Scene name retrive

### ISSUE THREAD

**Issue by ir0n87** [mthyden/PhillipsHueSIMPLSharp#27]
All is working but scene triggering and name retrive not working.
I tried also to reset HUB V1 to default conditions but same.

**Comment by mthyden** [comment]
I use those features daily and in my setup works as expected both scenes and name retrieve etc. I developed this on a V2 hub, So if there is an issue with the V1 hub I do not intend on modifying this implementation to provide special support for that platform. If you would like to provide me with your Groups/Lights/Scenes JSON data which I believe I have detailed in my readme section feel free and I can take a look and run it on my offline utility but like I said if the issue stems with the way the data is stored on a V1 hub you’re going to be on your own.

**Comment by mthyden** [comment]
https://developers.meethue.com/develop/get-started-2/ <https://developers.meethue.com/develop/get-started-2/>

**Comment by ir0n87** [comment]
{
	"RqYbjhlsmeGCakd": {
		"name": "Relax",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "mX1mZ_r01_d01"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:08",
		"version": 2
	},
	"TARrTJLPsiHnocf": {
		"name": "Lettura",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "ho0Oj_r01_d02"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:08",
		"version": 2
	},
	"sJk7Hk1B0I3KvGG": {
		"name": "Concentrazione",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "gDZIF_r01_d03"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"ABdSBfUQ7n5aCEg": {
		"name": "Energia",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "Iuqkp_r01_d04"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"z0rmzQW9UXCCja3": {
		"name": "Luce brillante",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "49VYt_r01_d05"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"0T36KNP6RvAjy5A": {
		"name": "Luce soffusa",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "NaKPV_r01_d06"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"WPXUStCjjFZ8YG1": {
		"name": "Luce notturna",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "YS2Pf_r01_d07"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"1CzrcD39Pn76D00": {
		"name": "Tramonto nella savana",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "InXFB_r01_d15"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:09",
		"version": 2
	},
	"q0HUIztjIKuoP0c": {
		"name": "Tramonto tropicale",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "MTrrR_r01_d16"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:10",
		"version": 2
	},
	"S8dERHM5Gjic4QM": {
		"name": "Aurora boreale",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "MtPJJ_r01_d17"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:10",
		"version": 2
	},
	"ZY6onh0oIIJEYIX": {
		"name": "Fioritura primaverile",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "QRiil_r01_d18"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:10",
		"version": 2
	}
}

**Comment by mthyden** [comment]
I need Groups / Lights as well, not just Scenes

**Comment by ir0n87** [comment]
{
	"1": {
		"name": "Omnimedia",
		"lights": [
			"2",
			"3",
			"1",
			"4"
		],
		"type": "Room",
		"state": {
			"all_on": true,
			"any_on": true
		},
		"class": "Office",
		"action": {
			"on": true,
			"bri": 254,
			"hue": 34069,
			"sat": 251,
			"effect": "none",
			"xy": [
				0.3145,
				0.3303
			],
			"ct": 156,
			"alert": "select",
			"colormode": "xy"
		}
	}
}

**Comment by ir0n87** [comment]
{
	"lights": {
		"1": {
			"state": {
				"on": true,
				"bri": 254,
				"hue": 34069,
				"sat": 251,
				"effect": "none",
				"xy": [
					0.3145,
					0.3303
				],
				"ct": 156,
				"alert": "select",
				"colormode": "xy",
				"reachable": true
			},
			"type": "Extended color light",
			"name": "DX1",
			"modelid": "LCT001",
			"manufacturername": "Philips",
			"uniqueid": "00:17:88:01:00:ec:98:91-0b",
			"swversion": "5.127.1.26581"
		},
		"2": {
			"state": {
				"on": true,
				"bri": 254,
				"hue": 34069,
				"sat": 251,
				"effect": "none",
				"xy": [
					0.3145,
					0.3303
				],
				"ct": 156,
				"alert": "select",
				"colormode": "xy",
				"reachable": true
			},
			"type": "Extended color light",
			"name": "SX1",
			"modelid": "LCT001",
			"manufacturername": "Philips",
			"uniqueid": "00:17:88:01:00:ec:94:b5-0b",
			"swversion": "5.127.1.26581"
		},
		"3": {
			"state": {
				"on": true,
				"bri": 254,
				"hue": 34069,
				"sat": 251,
				"effect": "none",
				"xy": [
					0.3145,
					0.3303
				],
				"ct": 156,
				"alert": "select",
				"colormode": "xy",
				"reachable": true
			},
			"type": "Extended color light",
			"name": "SX2",
			"modelid": "LCT001",
			"manufacturername": "Philips",
			"uniqueid": "00:17:88:01:00:dd:00:05-0b",
			"swversion": "5.130.1.30000"
		},
		"4": {
			"state": {
				"on": true,
				"bri": 254,
				"hue": 34069,
				"sat": 251,
				"effect": "none",
				"xy": [
					0.3145,
					0.3303
				],
				"ct": 156,
				"alert": "select",
				"colormode": "xy",
				"reachable": true
			},
			"type": "Extended color light",
			"name": "DX2",
			"modelid": "LCT001",
			"manufacturername": "Philips",
			"uniqueid": "00:17:88:01:00:ee:d1:02-0b",
			"swversion": "5.127.1.26581"
		}
	},
	"groups": {
		"1": {
			"name": "Omnimedia",
			"lights": [
				"2",
				"3",
				"1",
				"4"
			],
			"type": "Room",
			"state": {
				"all_on": true,
				"any_on": true
			},
			"class": "Office",
			"action": {
				"on": true,
				"bri": 254,
				"hue": 34069,
				"sat": 251,
				"effect": "none",
				"xy": [
					0.3145,
					0.3303
				],
				"ct": 156,
				"alert": "select",
				"colormode": "xy"
			}
		}
	},
	"config": {
		"name": "Philips hue",
		"zigbeechannel": 11,
		"bridgeid": "001788FFFE1C68BE",
		"mac": "00:17:88:1c:68:be",
		"dhcp": true,
		"ipaddress": "192.168.41.162",
		"netmask": "255.255.255.0",
		"gateway": "192.168.41.253",
		"proxyaddress": "none",
		"proxyport": 0,
		"UTC": "2020-09-28T18:20:22",
		"localtime": "none",
		"timezone": "none",
		"modelid": "BSB001",
		"datastoreversion": "59",
		"swversion": "01043155",
		"apiversion": "1.16.0",
		"swupdate": {
			"updatestate": 0,
			"checkforupdate": false,
			"devicetypes": {
				"bridge": false,
				"lights": [],
				"sensors": []
			},
			"url": "",
			"text": "",
			"notify": false
		},
		"linkbutton": false,
		"portalservices": false,
		"portalconnection": "disconnected",
		"portalstate": {
			"signedon": false,
			"incoming": false,
			"outgoing": false,
			"communication": "disconnected"
		},
		"factorynew": false,
		"replacesbridgeid": null,
		"backup": {
			"status": "idle",
			"errorcode": 0
		},
		"whitelist": {
			"00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER": {
				"last use date": "2020-09-28T17:57:18",
				"create date": "2020-09-28T17:28:20",
				"name": "Hue Bridge v1#iPhone di samu"
			},
			"bo1jprq9l4wnXh3msApguvYKAiE89s3ATcetKT7W": {
				"last use date": "2020-09-28T18:20:22",
				"create date": "2020-09-28T17:47:04",
				"name": "my_hue_app#crestron"
			},
			"suYOEqlXT0Pv5ihVyJntUgLGdAmD4V4h4nEnvCSj": {
				"last use date": "2020-09-28T17:57:18",
				"create date": "2020-09-28T17:53:39",
				"name": "WinHue"
			},
			"PbicsLttDkCFAfRzbcwaPc249LHTGLA00yBdU1Rq": {
				"last use date": "2020-09-28T18:20:22",
				"create date": "2020-09-28T18:07:24",
				"name": "my_hue_app#iphone peter"
			}
		}
	},
	"schedules": {},
	"scenes": {
		"RqYbjhlsmeGCakd": {
			"name": "Relax",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "mX1mZ_r01_d01"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:08",
			"version": 2
		},
		"TARrTJLPsiHnocf": {
			"name": "Lettura",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "ho0Oj_r01_d02"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:08",
			"version": 2
		},
		"sJk7Hk1B0I3KvGG": {
			"name": "Concentrazione",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "gDZIF_r01_d03"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"ABdSBfUQ7n5aCEg": {
			"name": "Energia",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "Iuqkp_r01_d04"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"z0rmzQW9UXCCja3": {
			"name": "Luce brillante",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "49VYt_r01_d05"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"0T36KNP6RvAjy5A": {
			"name": "Luce soffusa",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "NaKPV_r01_d06"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"WPXUStCjjFZ8YG1": {
			"name": "Luce notturna",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "YS2Pf_r01_d07"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"1CzrcD39Pn76D00": {
			"name": "Tramonto nella savana",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "InXFB_r01_d15"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:09",
			"version": 2
		},
		"q0HUIztjIKuoP0c": {
			"name": "Tramonto tropicale",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "MTrrR_r01_d16"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:10",
			"version": 2
		},
		"S8dERHM5Gjic4QM": {
			"name": "Aurora boreale",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "MtPJJ_r01_d17"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:10",
			"version": 2
		},
		"ZY6onh0oIIJEYIX": {
			"name": "Fioritura primaverile",
			"lights": [
				"1",
				"2",
				"3",
				"4"
			],
			"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
			"recycle": false,
			"locked": false,
			"appdata": {
				"version": 1,
				"data": "QRiil_r01_d18"
			},
			"picture": "",
			"lastupdated": "2020-09-28T17:31:10",
			"version": 2
		}
	},
	"rules": {},
	"sensors": {
		"1": {
			"state": {
				"daylight": null,
				"lastupdated": "none"
			},
			"config": {
				"on": true,
				"configured": false,
				"sunriseoffset": 30,
				"sunsetoffset": -30
			},
			"name": "Daylight",
			"type": "Daylight",
			"modelid": "PHDL00",
			"manufacturername": "Philips",
			"swversion": "1.0"
		}
	},
	"resourcelinks": {}
}

**Comment by mthyden** [comment]
Thanks, will circle back once I run it through

**Comment by mthyden** [comment]
Found the issue in your bridge data, which I was correct your V1 bridge API is slightly different than the V2 bridge API. The V1 Bridge is not receiving any more support as of this past April so I do not intend on making changes. My recommendation would be to get a V2 bridge.

Originally the Hue API did not provide this parameter associating a scene to a group, in an earlier version of my module I would have to compare which bulbs were in a scene with which bulbs are in a room. When the API was updated with this group parameter it made that association directly between the group and the scene which was much more efficient so I updated my implementation to utilize that. So if you insist on continuing to use your V1 bridge you will have to most likely use my Commit from August 20th 2019. That appears to be where I changed to the new Group/scene association model. But like I said best thing should be to get a V2 bridge.

V2 sample Scene:
	"SpQ1BZyYBA7OJ7q": {
		"name": "Dorri green",
		"type": "GroupScene",
		"group": "7”, <———*****MISSING FROM YOUR DATA********
		"lights": [
			"16"
		],
		"owner": "f22a5c4c-b0a8-4174-8738-398ed53f78c0",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "rHgn6_r07_d99"
		},
		"picture": "",
		"lastupdated": "2020-02-25T02:40:52",
		"version": 2
	}

V1 sample Scene:
	"RqYbjhlsmeGCakd": {
		"name": "Relax",
		"lights": [
			"1",
			"2",
			"3",
			"4"
		],
		"owner": "00PAABZTw7rgBphIpz3p10FlymLe1T6hCleg65ER",
		"recycle": false,
		"locked": false,
		"appdata": {
			"version": 1,
			"data": "mX1mZ_r01_d01"
		},
		"picture": "",
		"lastupdated": "2020-09-28T17:31:08",
		"version": 2
	}

**Comment by mthyden** [comment]
closing issue as it only pertains to V1 bridge which is no longer supported
