### ISSUE TITLE
scenes

### ISSUE THREAD

**Issue by Chibale11** [mthyden/PhillipsHueSIMPLSharp#3]
Hello, 

Love the module. One question. Have you worked out the issue with scenes?

**Comment by mthyden** [comment]
Scenes should be pretty solid at this point, have you run into an issue?

**Comment by Chibale11** [comment]
Yes using version 1.2 from git hub. Is that the most current?
		
		

		Afiba Edwards
	




On Thu, Jul 20, 2017 at 11:34 AM -0400, "Monte" <notifications@github.com> wrote:










Scenes should be pretty solid at this point, have you run into an issue?

**Comment by mthyden** [comment]
whats on github is the latest.

**Comment by Chibale11** [comment]
Ok great I'll try again. 
		
		

		Afiba Edwards
	




On Thu, Jul 20, 2017 at 11:39 AM -0400, "Monte" <notifications@github.com> wrote:










whats on github is the latest.

**Comment by mthyden** [comment]
you get this working?

**Comment by Chibale11** [comment]
Have not had a chance to work on it. Major projects going on. Will update
you when I get to look at it again. ;Thanks so much for following up.
