### ISSUE TITLE
Crestron Home Extension?

### ISSUE THREAD

**Issue by adorsett** [mthyden/PhillipsHueSIMPLSharp#30]
Any plans to make this a Crestron Home Extension?

Thanks!
Andrew

**Comment by mthyden** [comment]
Yes, I’m reviewing the plug-in platform actually and am planning on creating a driver for it. I don’t have an ETA as of yet.

**Comment by mthyden** [comment]
I'd prefer not to keep this as an open issue as it's a feature request and technically an entirely different product, closing this.
