### ISSUE TITLE
Last Upgrade module won't compile on serie 3 

### ISSUE THREAD

**Issue by metronomeout** [mthyden/PhillipsHueSIMPLSharp#31]
Hello,

Thanks for your work ! I Can't compile the last version of your modules on 3 series processors. There are only available on 4 series ?

![Cp](https://user-images.githubusercontent.com/52577712/103544764-e219af00-4ea0-11eb-9f5a-10260074f528.png)

Thanks

**Comment by mthyden** [comment]
I just compiled them for 3-series and was fine for me.

I know a few others who tried the newest versions of the modules and were good as well.

Based on the compiler log it doesn’t look like perhaps you are using the latest CLZ which includes the new CT event handlers

**Comment by metronomeout** [comment]
I solved the problem ! I juste make some clearing of my database and it's ok now.

Thanks
