### ISSUE TITLE
Missing HueProcessor V2.0.umc

### ISSUE THREAD

**Issue by LukeAus2** [mthyden/PhillipsHueSIMPLSharp#36]
Appears to be missing the in PhilipsHue Demo v2.4 3-series program. 

Any assistance appreciated

TIA LH

**Comment by mthyden** [comment]
Unzip the compiled archive, its in there SIMPL/PhilipsHue Demo v2.4 3-series_compiled.zip

**Comment by mthyden** [comment]
non-issue
