### ISSUE TITLE
Can't open demo

### ISSUE THREAD

**Issue by danross78** [mthyden/PhillipsHueSIMPLSharp#4]
Is it possible to load some screen shots of your setup? I can't seem to open the demos.

**Comment by mthyden** [comment]
what specifically can't you open? there is a PhilipsHue Demo v1.4_compiled which has a small demo program with all the modules in it. in the UI folder is the sample UI project, I did notice that it didn't include the custom theme for the sliders which I just now sync'd up but shouldn't have any issues. Provide some specifics and I can assist.

**Comment by danross78** [comment]
I tried uploading a screen shot of the error but it isn't working. 

I get the following error when I try to open one of your sample programs:

Invalid file signature, extension, access rights or filename length.

**Comment by mthyden** [comment]
Haven't heard of any problems opening up the archives, below is a dropbox link to the same archive file https://www.dropbox.com/s/nb9gcf0598p3ihs/PhillipsHue%20Demo%20v1.4_compiled.zip?dl=0

**Comment by mthyden** [comment]
Its a windows thing, be sure you put the archive on your desktop and not in a super deep path in your user directory, then try to import, or simply unzip the archive on a shallower file path.
