### ISSUE TITLE
Error getting the APIkey

### ISSUE THREAD

**Issue by toeas** [mthyden/PhillipsHueSIMPLSharp#9]
Hello.

Having problem with the Init process. Cant get the APIKEY to work. And i cant find out why.
Any ide?

![debug](https://user-images.githubusercontent.com/34315788/33677300-897ef4cc-dab8-11e7-9237-75417b807971.jpg)

**Comment by mthyden** [comment]
hmm your the second person I’ve heard having issues getting the API key. stupid question but before you hit hue_init you did press the physical bridge button correct? if so I’m not sure what the problem could be. I’m assuming this proc has never had a key issued yet by a bridge, essentially a new deployment? What program slot is it running in? What is the processor you have it running on? My current suspicion is that the key storing mechanism into the processor’s NVRAM is happening too quickly before the NVRAM storage is fully initialized but unfortunately without being able to duplicate the issue on my end it’s hard to tell. I have an updated release that is on deck, I just need to squash a bug related to the individual bulb module, I’ll add some protections to the API key init and storage while I’m at it.

On Dec 6, 2017, at 1:06 PM, toeas <notifications@github.com> wrote:

Hello.

Having problem with the Init process. Cant get the APIKEY to work. And i cant find out why.
Any ide?

 <https://user-images.githubusercontent.com/34315788/33677300-897ef4cc-dab8-11e7-9237-75417b807971.jpg>

**Comment by toeas** [comment]
Hello.

I did try hit the button before the program started and ever Manuel after using toolbox with the same result.
I have a RMC3 so there is only 1 program slot at the moment.
Could i do anything from here to help you find out more?

**Comment by mthyden** [comment]
send me an email to mthyden@gmail.com <mailto:mthyden@gmail.com> and I’ll send you a beta version I’m working. I added some protections in the registration routine and temporarily will print out to console what the proc thinks is the key if it has a value stored in it’s datastore. 

On Dec 7, 2017, at 1:49 AM, toeas <notifications@github.com> wrote:

Hello.

I did try hit the button before the program started and ever Manuel after using toolbox with the same result.
I have a RMC3 so there is only 1 program slot at the moment.
Could i do anything from here to help you find out more?

**Comment by Mjrtoo** [comment]
I have the very same problem with registration, sending you an email.

**Comment by mthyden** [comment]
thanks for letting me know, I sent the beta to you.

On Dec 7, 2017, at 7:33 PM, Mjrtoo <notifications@github.com> wrote:

I have the very same problem with registration, sending you an email.

**Comment by Mjrtoo** [comment]
I did make sure the new .clz was used…

**Comment by mthyden** [comment]
Yeah it was that one statement in debug was added this morning, was expecting it to fail prior to that though, very puzzling, I am actually thinking the API key request to the bridge may have changed with a recent bridge software update, which would explains folks who have had a key issued prior to whatever update it was have systems still working but new requests fail. I’ll check it out should be a quick change once identified.

**Comment by Mjrtoo** [comment]
Right on  this is a round bridge, v1, if that matters, potentially. 
I'd be happy to test whatever... Thanks!  Thursday, 07 December 2017, 07:56PM -06:00 from Monte Thyden  notifications@github.com :

>Yeah it was that one statement in debug was added this morning, was expecting it to fail prior to that though, very puzzling, I am actually thinking the API key request to the bridge may have changed with a recent bridge software update, which would explains folks who have had a key issued prior to whatever update it was have systems still working but new requests fail. I’ll check it out should be a quick change once identified.
>
>Sent from my iPad
>

**Comment by mthyden** [comment]
I’ve had v1 and v2 work previously so it shouldn’t be an issue, I’ll get it sorted out

**Comment by toeas** [comment]
Hello.

Did you get my mail?

**Comment by mthyden** [comment]
I did not, here is the beta 
https://www.dropbox.com/s/kkrl2qab0ox4520/PhillipsHue%20Demo%20v2.2_compiled.zip?dl=0


On Dec 8, 2017, at 6:00 AM, toeas <notifications@github.com> wrote:

Hello.

Did you get my mail?

**Comment by toeas** [comment]
Hello.

I sent you one more mail to see if you got if.
The beta works for me. I got the key now.

Andreas

**Comment by toeas** [comment]
Hello.

Now i have a bulb problem. What am i doing wrong ?

![debug2](https://user-images.githubusercontent.com/34315788/33796124-f6db026c-dcee-11e7-884d-740309a5f17e.jpg)

**Comment by toeas** [comment]
It do not go online for some reason

**Comment by mthyden** [comment]
I’ve tweaked and tested the beta, its now pushed to github. if you run into issues and think it is as a result of your specific bridge data I can run through your bridge data through my offline test program

instructions on how to perform bridge requests for your bridge data are found: https://developers.meethue.com/documentation/getting-started <https://developers.meethue.com/documentation/getting-started>
In the past I’ve requested from folks, “lights”, “groups”, and “scenes”.

On Dec 10, 2017, at 11:19 AM, toeas <notifications@github.com> wrote:

It do not go online for some reason

**Comment by toeas** [comment]
I downloaded the last files but still cant get any were. What im i missing.
It gets the key, and then "Error getting bulbs: System.ArgumentNullExeption: Value can be null"
And after going throw the inti its not online...

**Comment by mthyden** [comment]
The api key issue has been resolved, follow the instructions on how to pull your bridge data and when I have time I can run it through my offline test program (which is also part of the visual studio source, its certainly possible there is something in your bridge data preventing it from pulling down correctly

**Comment by mthyden** [comment]
I found the problem in your bulb data, you have 1 Ikea bulb in the mix that has a different data structure then the philips bulbs, it uses a different color mode ct, so I'll need to create a new bulb type for the Ikea ones and handle the ct values differently, for now I'd suggest removing your ikea bulb and you should be good to go.
